# Generated by Django 5.0.4 on 2024-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(null=True, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
